### ISSUE TITLE
About us section improvement

### ISSUE THREAD

**Issue by kairveeehh** [SmartGrid-ETHIndia/Smart-grid#21]
hi @Mayank2808sharma I would like to improve the UI of the footer/about us page and make it more visually appealing 

### please assign this issue to me under GSSoC'24 
![Screenshot 2024-05-09 194548](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/145572028/3f5a6949-2871-4514-8182-fcc98c283e29)

**Comment by Mayank2808sharma** [comment]
Hello @kairveeehh 
I have assigned it to you.
Go ahead and let me know if you need any help

**Comment by kairveeehh** [comment]
@Mayank2808sharma I will be needing help with setting it up locally and the commands to be run

**Comment by Mayank2808sharma** [comment]
@kairveeehh 
First, install the packages using **npm install**
Then use **npm run dev** to run it on your local host

**Comment by kairveeehh** [comment]
> 👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

bro the issuesw already is assigned to me
