### ISSUE TITLE
Feature - a guide to metamask 

### ISSUE THREAD

**Issue by kairveeehh** [SmartGrid-ETHIndia/Smart-grid#22]
for those who dont have knowledge about metamask we can add a guide me button which can guide the newcomers about it and steps to proceed with

**Comment by Anayverma** [comment]
@kairveeehh sir , I have developed two dapp using metamask wallet. Hence I would be contributing to this issue. Please assign it to me under gssoc24.

**Comment by kairveeehh** [comment]
> @kairveeehh sir , I have developed two dapp using metamask wallet. Hence I would be contributing to this issue. Please assign it to me under gssoc24.

hii , I am a contributor and have raised this issue as I am already into web3 , please find different issues and raise them instead of this

**Comment by Mayank2808sharma** [comment]
@kairveeehh 
Some is working on readme 
They have added about it over there
so no need I guess
