### ISSUE TITLE
Improve Header UI and Metamask address slice.

### ISSUE THREAD

**Issue by ENZOMOTIVE** [SmartGrid-ETHIndia/Smart-grid#25]
![Screenshot 2024-05-09 231621](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/91072069/9e851e25-3a1a-4d15-a850-76f60933b004)
Hey, @Mayank2808sharma  I would like to improve the header part to make it visually appealing and also make the meta mask address display sliced so that it does not showcase the whole address, as this may lead to issues in the future. So please assign me the task.

**Comment by Mayank2808sharma** [comment]
@ENZOMOTIVE 
Go ahead, I have assigned the issue to you.

**Comment by ENZOMOTIVE** [comment]
![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/91072069/60b5dc5b-2f46-4b70-89f0-c786d9c98397)
I have made the changes and created a pull request.

**Comment by ENZOMOTIVE** [comment]
@Mayank2808sharma  i have pulled the request to the master branch but deployement failed is showing. the code is working perfectly on my machine

**Comment by ENZOMOTIVE** [comment]
I did it but it fails I only made some typescript and css changes and
nothings seems an error to me. But the deployment failed. on which branch
do I need to ull because I pulled on the master.

**Comment by Mayank2808sharma** [comment]
After making some changes, make sure to run `npm run build` to check if the build is failing or not. If it fails, there might be an issue with your code.

**Comment by ENZOMOTIVE** [comment]
@Mayank2808sharma Succesfully merged the pull request thank you. So, now do I need to do something additional like how will I get points that I made the contribution.
