### ISSUE TITLE
Hero Section not optimized for Mobile Version.

### ISSUE THREAD

**Issue by NilanchalaPanda** [SmartGrid-ETHIndia/Smart-grid#26]
The hero section of SmartGrid is properly designed for Desktop version, but on mobile view it is not center aligned with overlapping of the image and Heading Text.

I would love to work on this issue and contribute to SmartGrid-ETHIndia as a GSSoC'24 Contributor. Looking forward to your response.

IMAGE :
![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/110488337/5809ad31-181f-491d-896f-7bc95abcb455)

**Comment by Mayank2808sharma** [comment]
@NilanchalaPanda 
I have assigned it to you

**Comment by NilanchalaPanda** [comment]
Thanks for the update @Mayank2808sharma. Will starting working upon the issue 👍🏻
