### ISSUE TITLE
BUG: Navigation bar is not visible while viewing the EVMap

### ISSUE THREAD

**Issue by dhanyashreem2400** [SmartGrid-ETHIndia/Smart-grid#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navigation bar on top is not visible while viewing the EVMap 

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/97956917/628a204c-fd0b-4adb-98a2-31d5cab8dbe5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ENZOMOTIVE** [comment]
It was because of the styling. I completed this in my pull request so no worries.         Happy Coding
