### ISSUE TITLE
Feat: Add a Contributing.md file

### ISSUE THREAD

**Issue by nirban256** [SmartGrid-ETHIndia/Smart-grid#50]
### Describe the feature

# Working

This project should contain a contributing.md file which will help other users to understand how to contribute to this repo for different issues and get there pr merged.

### Add ScreenShots

I am not adding any ss now 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nirban256** [comment]
Please add gssoc label and allow me to contribute to it @Mayank2808sharma

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign this task to me.

**Comment by Mayank2808sharma** [comment]
@nirban256 
Please go ahead

**Comment by nirban256** [comment]
Thanks @Mayank2808sharma

**Comment by nirban256** [comment]
As the pr is merged I am closing this issue @Mayank2808sharma
