### ISSUE TITLE
Add a current location button to the EV map

### ISSUE THREAD

**Issue by veer-chheda** [SmartGrid-ETHIndia/Smart-grid#51]
### Describe the feature

Currently, there's no current location button to redirect the map to your location; it is fixed to Delhi. A redirect button would improve the user experience.

### Add ScreenShots

<img width="1440" alt="image" src="https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/114056626/9cf88848-8fb9-4410-b316-9d5728e69ce7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by veera6513** [comment]
Please assign this issue to me

**Comment by Mayank2808sharma** [comment]
some one already working on this
