### ISSUE TITLE
MISSING content in Readme.md file

### ISSUE THREAD

**Issue by anushkamahajan901** [SmartGrid-ETHIndia/Smart-grid#54]
### What's wrong with the existing documentation

An essential asset content in a Readme file for directing prospective contributors on effective project engagement is a comprehensive guide detailing the process is missing.

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/85194446/2122c453-637a-4bac-88e6-c206650aef1b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
@anushkamahajan901 
Some one is already working on the readmefile
