### ISSUE TITLE
DOC: Add Code of Conduct 

### ISSUE THREAD

**Issue by aasthakourav20** [SmartGrid-ETHIndia/Smart-grid#57]
### What's wrong with the existing documentation

This repo has no Code of Conduct

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
Go ahead
I have assigned it to you
@aasthakourav20

**Comment by aasthakourav20** [comment]
> @Mayank2808sharma this is PM of Gssoc, we have mailed regarding to add me into the repo. so I can handle the label issues by contributor

Thank you so much sir
