### ISSUE TITLE
Feat: Truncate metamask account address

### ISSUE THREAD

**Issue by Ravi62026** [SmartGrid-ETHIndia/Smart-grid#58]
### Describe the feature

- I want that the long account address is truncated to a shorter address which can be copied when clicked
- nav-bar options are also not well, can improve

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/128376014/c2367846-ce63-48f0-8336-9a6d5ccb5738)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
@Ravi62026 
Some one already working on this issue
if they don't fix it, I will assign it to you.
