### ISSUE TITLE
DOC :  Readme file with no project description 

### ISSUE THREAD

**Issue by aasthakourav20** [SmartGrid-ETHIndia/Smart-grid#65]
### What's wrong with the existing documentation

No Documentation is present on the Readme file . For the GSSoC'24 open source contribution purpose , Readme file with proper
project description is required 
 

### Add ScreenShots

![Screenshot (205)](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/148269962/2e6cf8d4-4148-4c57-be36-aa116d4e129a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aasthakourav20** [comment]
Hey @Mayank2808sharma , please assign this issue to me under GSSoC'24

**Comment by Mayank2808sharma** [comment]
Hey @aasthakourav20 
Someone is already working on the readme
