### ISSUE TITLE
Feat: Adding more options for Wallet

### ISSUE THREAD

**Issue by dhanyashreem2400** [SmartGrid-ETHIndia/Smart-grid#69]
### Describe the feature

As of now there is only one option for wallet, i.e Metamask , so I would like to add more wallets like Coinbase or Wallet Connect

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/97956917/c2991f54-a9f2-47f5-9470-d8d348036847)

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/97956917/83fbf6ad-ef0b-40e5-99f2-a57022737832)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
someone is already working on this
