### ISSUE TITLE
BUG: Website not Responsive in Mobile Screen

### ISSUE THREAD

**Issue by PranavKeshav24** [SmartGrid-ETHIndia/Smart-grid#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The entire Smart-grid website is not responsive for mobile screens and multiple other screens. The elements are out of the place in the mobile screen.

Screenshots:
![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/127531721/6f177e5b-9a99-4260-b5b7-43c6b9abf55b)
![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/127531721/89636e66-304f-48b1-a70a-c913bbaf6d31)
![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/127531721/d0393ef8-9ec2-45f3-87c4-910f46a141c4)

Please assign me this issue. I would love to work on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
someone already working on this
