### ISSUE TITLE
Feat: Add a Contact Us Page

### ISSUE THREAD

**Issue by PranavKeshav24** [SmartGrid-ETHIndia/Smart-grid#75]
### Describe the feature

In order to improve our customer service and ensure better communication with our users, we need to add a "Contact Us" page to our website. The present "Contact Us" link in the footer leads to ipfs.tech website. A contact us form where users can submit their queries or feedback. The form should ask for the user's name, email, and their message.

Please assign this issue to me. I would love to work on it.

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/127531721/35bb2367-e7a3-4571-bbbf-292e785e7e57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
do you still want to work on this

**Comment by PranavKeshav24** [comment]
@Mayank2808sharma Please assign this issue to me. I would be very happy to work on it.

**Comment by Mayank2808sharma** [comment]
That's great to hear

Go ahead, I have assigned it to you
