### ISSUE TITLE
Readme.md can be more fascinating_DOC:

### ISSUE THREAD

**Issue by Meetjain1** [SmartGrid-ETHIndia/Smart-grid#81]
### What's wrong with the existing documentation

**What Docs changes are you proposing?**
currently readme file lacks some sections that if we add , then readme file can be more attractive to the contributors

**Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?**
current readme is not upto the mark its looking like learn.md file

**Describe the solution you'd like**
like contributors section , code of conduct section, working video of our project etc 

@Mayank2808sharma assign this issue to me I will add an attractive readme file .
I am working under gssoc24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
the exisiting readme is good
