### ISSUE TITLE
Feat:Adiition of Authentication

### ISSUE THREAD

**Issue by khy05dua** [SmartGrid-ETHIndia/Smart-grid#85]
### Describe the feature

the idea is to add authentication to allow  users to sign up and login securely using their blockchain wallet addresses,in order to ensure integrity and security of user data.Can be implemented on the home page.
Please assign me into this task.

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/141299441/d53af378-b159-46df-aca3-49dbfba4af09)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by khy05dua** [comment]
@Mayank2808sharma please assign me to this task

**Comment by Mayank2808sharma** [comment]
I think signup is not required
users are already using their wallet to sign in
