### ISSUE TITLE
Feat:Replace the Twitter Logo with X  for GSSOC'24 - Level 3

### ISSUE THREAD

**Issue by codercake** [SmartGrid-ETHIndia/Smart-grid#88]
### Describe the feature

**Description**

Replace the Twitter logo with an "X" icon throughout the platform. Use Tailwind to ensure seamless integration of the "X" icon into the Twitter interface.

**Benefits:**
1. Adds a fresh and innovative element to the Twitter interface.
2. Showcases the versatility of Next.js and CSS in frontend development.
3. Provides an opportunity for contributors to enhance their skills in web development and design

**Assignment:**

Please assign this issue to me https://github.com/codercake under the "gssoc" and "level 3" label.

### Add ScreenShots

![image](https://github.com/SmartGrid-ETHIndia/Smart-grid/assets/117517206/4a8cb8af-a5d9-4a84-8f59-f7344dbc5304)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayank2808sharma** [comment]
I really dont think there is a need for this

please create an issue first and don't raise a pr till that issue is assigned to you
